spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 1df3230b362991
    password: ff52c428fce14a
    properties:
      smtp:
        auth:true
    starttls:
          enable:true
