example:
  string: >
   Hello Pdp
   Hello Pdp
   Hello Pdp
   Hello Pdp
   Hello Pdp
   Hello Pdp
   Hello Pdp
   Hello Pdp
  languages:
   - Java
   - Kotlin
   - phyton
  person:
    id: ${random.uuid}
    firstName: Behzod
    lastName: Farmonov
    fullName: ${example.person.firstName} ${example.person.lastName}
    age: 21

